export const Tickers = [
  {id: 1, Key:"RELIANCE.NS", Value:"RELIANCE.NS", news:"RI", name:"reliance-industries-share-price"},
  {id: 2, key:"TCS.NS", Value:"TCS.NS", news:"TCS", name:"tata-consultancy-services-share-price"},
  {id: 3, Key:"INFY.NS", Value:"INFY.NS", news:"IT", name:"infosys-share-price"},
  {id: 4, Key:"HDFCBANK.NS", Value:"HDFCBANK.NS", news:"HDF01", name:"hdfc-bank-share-price"},
  {id: 5, Key:"ICICIBANK.NS", Value:"ICICIBANK.NS", news:"ICI02", name:"icici-bank-share-price"},
  {id: 6, Key:"SBIN.NS", Value:"SBIN.NS", news:"SBI", name:"state-bank-of-india-share-price"},
];


export const Invest_option = [
   {id: 1, key:"stocks", Value:"stocks"},
   {id: 2, key:"bonds", Value:"bonds"},
   {id: 3, key:"real_estate", Value:"real_estate"},
   {id: 4, key:"gold", Value:"gold"},
];

export const Risk_level = [
  {id: 1, key: "Low", Value:"Low"},
  {id: 2, key: "Medium", Value:"Medium"},
  {id: 3, key: "High", Value:"High"}
]

export const Industries = [
  { id: 1, key: "Abrasives", Value: "Abrasives" },
  { id: 2, key: "Advertising & Media", Value: "Advertising & Media" },
  { id: 3, key: "Agriculture", Value: "Agriculture" },
  { id: 4, key: "Air Conditioners", Value: "Air Conditioners" },
  { id: 5, key: "Airlines", Value: "Airlines" },
  { id: 6, key: "Airport Management Services", Value: "Airport Management Services" },
  { id: 7, key: "Aluminium & Aluminium Products", Value: "Aluminium & Aluminium Products" },
  { id: 8, key: "Amusement Parks/Recreation/Club", Value: "Amusement Parks/Recreation/Club" },
  { id: 9, key: "Animal Feed", Value: "Animal Feed" },
  { id: 10, key: "Aquaculture", Value: "Aquaculture" },
  { id: 11, key: "Auto Ancillary", Value: "Auto Ancillary" },
  { id: 12, key: "Automobile Two & Three Wheelers", Value: "Automobile Two & Three Wheelers" },
  { id: 13, key: "Automobiles - Dealers & Distributors", Value: "Automobiles - Dealers & Distributors" },
  { id: 14, key: "Automobiles - Passenger Cars", Value: "Automobiles - Passenger Cars" },
  { id: 15, key: "Automobiles-Tractors", Value: "Automobiles-Tractors" },
  { id: 16, key: "Automobiles-Trucks/Lcv", Value: "Automobiles-Trucks/Lcv" },
  { id: 17, key: "Bank - Private", Value: "Bank - Private" },
  { id: 18, key: "Bank - Public", Value: "Bank - Public" },
  { id: 19, key: "Batteries", Value: "Batteries" },
  { id: 20, key: "Bearings", Value: "Bearings" },
  { id: 21, key: "BPO/ITeS", Value: "BPO/ITeS" },
  { id: 22, key: "Breweries & Distilleries", Value: "Breweries & Distilleries" },
  { id: 23, key: "Business Support", Value: "Business Support" },
  { id: 24, key: "Cable", Value: "Cable" },
  { id: 25, key: "Carbon Black", Value: "Carbon Black" },
  { id: 26, key: "Castings/Forgings", Value: "Castings/Forgings" },
  { id: 27, key: "Cement & Construction Materials", Value: "Cement & Construction Materials" },
  { id: 28, key: "Ceramics/Marble/Granite/Sanitaryware", Value: "Ceramics/Marble/Granite/Sanitaryware" },
  { id: 29, key: "Chemicals", Value: "Chemicals" },
  { id: 30, key: "Cigarettes/Tobacco", Value: "Cigarettes/Tobacco" },
  { id: 31, key: "Compressors / Pumps", Value: "Compressors / Pumps" },
  { id: 32, key: "Construction - Real Estate", Value: "Construction - Real Estate" },
  { id: 33, key: "Construction Vehicles", Value: "Construction Vehicles" },
  { id: 34, key: "Consumer Durables - Domestic Appliances", Value: "Consumer Durables - Domestic Appliances" },
  { id: 35, key: "Consumer Durables - Electronics", Value: "Consumer Durables - Electronics" },
  { id: 36, key: "Consumer Food", Value: "Consumer Food" },
  { id: 37, key: "Courier Services", Value: "Courier Services" },
  { id: 38, key: "Cycles", Value: "Cycles" },
  { id: 39, key: "Defence", Value: "Defence" },
  { id: 40, key: "Depository Services", Value: "Depository Services" },
  { id: 41, key: "Detergents & Soaps", Value: "Detergents & Soaps" },
  { id: 42, key: "Diamond & Jewellery", Value: "Diamond & Jewellery" },
  { id: 43, key: "Diesel Engines", Value: "Diesel Engines" },
  { id: 44, key: "Diversified", Value: "Diversified" },
  { id: 45, key: "Dyes & Pigments", Value: "Dyes & Pigments" },
  { id: 46, key: "e-Commerce", Value: "e-Commerce" },
  { id: 47, key: "Edible Oil", Value: "Edible Oil" },
  { id: 48, key: "Educational Institutions", Value: "Educational Institutions" },
  { id: 49, key: "Electric Equipment", Value: "Electric Equipment" },
  { id: 50, key: "Electrodes & Welding Equipment", Value: "Electrodes & Welding Equipment" },
  { id: 51, key: "Electronics - Components", Value: "Electronics - Components" },
  { id: 52, key: "Engineering", Value: "Engineering" },
  { id: 53, key: "Engineering - Construction", Value: "Engineering - Construction" },
  { id: 54, key: "Engineering - Industrial Equipments", Value: "Engineering - Industrial Equipments" },
  { id: 55, key: "Engineering Consultancy", Value: "Engineering Consultancy" },
  { id: 56, key: "Environmental Services", Value: "Environmental Services" },
  { id: 57, key: "Fasteners", Value: "Fasteners" },
  { id: 58, key: "Ferro & Silica Manganese", Value: "Ferro & Silica Manganese" },
  { id: 59, key: "Fertilizers", Value: "Fertilizers" },
  { id: 60, key: "Film Production, Distribution & Entertainment", Value: "Film Production, Distribution & Entertainment" },
  { id: 61, key: "Finance - Asset Management", Value: "Finance - Asset Management"},
  { id: 62, key: "Finance - Housing", Value: "Finance - Housing"},
  { id: 63, key: "Finance - Investment", Value: "Finance - Investment"},
  { id: 64, key: "Finance - NBFC", Value: "Finance - NBFC"},
  { id: 65, key: "Finance - Others", Value: "Finance - Others"},
  { id: 66, key: "Finance - Stock Broking", Value: "Finance - Stock Broking"},
  { id: 67, key: "Finance Term Lending", Value: "Finance Term Lending"},
  { id: 68, key: "Fintech", Value: "Fintech"},
  { id: 69, key: "Floriculture", Value: "Floriculture"},
  { id: 70, key: "Footwear", Value: "Footwear"},
  { id: 71, key: "Forgings", Value: "Forgings"},
  { id: 72, key: "Gas Transmission/Marketing", Value: "Gas Transmission/Marketing"},
  { id: 73, key: "Glass", Value: "Glass"},
  { id: 74, key: "Hospital & Healthcare Services", Value: "Hospital & Healthcare Services"},
  { id: 75, key: "Hotel, Resort & Restaurants", Value: "Hotel, Resort & Restaurants"},
  { id: 76, key: "Household & Personal Products", Value: "Household & Personal Products"},
  { id: 77, key: "Industrial Gases & Fuels", Value: "Industrial Gases & Fuels"},
  { id: 78, key: "Insurance", Value: "Insurance"},
  { id: 79, key: "IT - Education", Value: "IT - Education"},
  { id: 80, key: "IT - Hardware", Value: "IT - Hardware"},
  { id: 81, key: "IT - Networking", Value: "IT - Networking"},
  { id: 82, key: "IT - Software", Value: "IT - Software"},
  { id: 83, key: "Laminates/Decoratives", Value: "Laminates/Decoratives"},
  { id: 84, key: "Leather", Value: "Leather"},
  { id: 85, key: "Logistics", Value: "Logistics"},
  { id: 86, key: "Lubricants", Value: "LubricantsNBFC"},
  { id: 88, key: "Medical Equipment/Supplies/Accessories", Value: "Medical Equipment/Supplies/Accessories"},
  { id: 89, key: "Metal - Ferrous", Value: "Metal - Ferrous"},
  { id: 90, key: "Metal - Non Ferrous", Value: "Metal - Non Ferrous"},
  { id: 91, key: "Mining & Minerals", Value: "Mining & Minerals"},
  { id: 92, key: "Miscellaneous", Value: "Miscellaneous"},
  { id: 93, key: "Oil Exploration", Value: "Oil Exploration"},
  { id: 94, key: "Packaging", Value: "Packaging"},
  { id: 95, key: "Paints", Value: "Paints"},
  { id: 96, key: "Paper & Paper Products", Value: "Paper & Paper Products"},
  { id: 97, key: "Pesticides & Agrochemicals", Value: "Pesticides & Agrochemicals"},
  { id: 98, key: "Petrochemicals", Value: "Petrochemicals"},
  { id: 99, key: "Pharmaceuticals & Drugs", Value: "Pharmaceuticals & Drugs"},
  { id: 100, key: "Photographic Products", Value: "Photographic Products"},
  { id: 101, key: "Plastic Products", Value: "Plastic Products"},
  { id: 102, key: "Port", Value: "Port"},
  { id: 103, key: "Power Generation/Distribution", Value: "Power Generation/Distribution"},
  { id: 104, key: "Printing & Stationery", Value: "Printing & Stationery"},
  { id: 105, key: "Printing And Publishing", Value: "Printing And Publishing"},
  { id: 106, key: "Professional Services", Value: "Professional Services"},
  { id: 107, key: "Railways Wagons", Value: "Railways Wagons"},
  { id: 108, key: "Ratings", Value: "Ratings"},
  { id: 109, key: "Refineries", Value: "Refineries"},
  { id: 110, key: "Refractories", Value: "Refractories"},
  { id: 111, key: "Restaurants", Value: "Restaurants"},
  { id: 112, key: "Retailing", Value: "Retailing"},
  { id: 113, key: "Rubber Products", Value: "Rubber Products"},
  { id: 114, key: "Ship Building", Value: "Ship Building"},
  { id: 115, key: "Shipping", Value: "Shipping"},
  { id: 116, key: "Solvent Extraction", Value: "Solvent Extraction"},
  { id: 117, key: "Steel & Iron Products", Value: "Steel & Iron Products"},
  { id: 118, key: "Steel/Sponge Iron/Pig Iron", Value: "Steel/Sponge Iron/Pig Iron"},
  { id: 119, key: "Sugar", Value: "Sugar"},
  { id: 120, key: "Tea/Coffee", Value: "Tea/Coffee"},
  { id: 121, key: "Telecom-Infrastructure", Value: "Telecom-Infrastructure"},
  { id: 122, key: "Telecommunication - Equipment", Value: "Telecommunication - Equipment"},
  { id: 123, key: "Telecommunication - Service Provider", Value: "Telecommunication - Service Provider"},
  { id: 124, key: "Textile", Value: "Textile"},
  { id: 125, key: "Textile - Machinery", Value: "Textile - Machinery"},
  { id: 126, key: "Textile - Manmade Fibres", Value: "Textile - Manmade Fibres"},
  { id: 127, key: "Textile - Spinning", Value: "Textile - Spinning"},
  { id: 128, key: "Textile - Weaving", Value: "Textile - Weaving"},
  { id: 129, key: "Trading", Value: "Trading"},
  { id: 130, key: "Transmission Towers / Equipments", Value: "Transmission Towers / Equipments"},
  { id: 131, key: "TV Broadcasting & Software Production", Value: "TV Broadcasting & Software Production"},
  { id: 132, key: "Tyres & Allied", Value: "Tyres & Allied"},
  { id: 133, key: "Watches & Accessories", Value: "Watches & Accessories"},
  { id: 134, key: "Wood & Wood Products", Value: "Wood & Wood Products"}
];
